[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

eclipse.project.name = appName + '-simulation'

dependencies {
    implementation "com.google.code.gson:gson:$gsonVersion"

    testImplementation "org.junit.jupiter:junit-jupiter:$junitVersion"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat = "full"
    }
}